const CoilsRedis = require('coils-redis')
let QueueManager = require('../lib/index')
let application = {}
CoilsRedis.mounted(application)
QueueManager.mounted(application)

application._queueManger.changeStatus('quiet')
application._queueManger.changeConcurrency(19)
// application._queueManger.add('HelloJob').set({wait: 200}).perform_now('world')
application._queueManger.add('HelloJob').set({wait: 0}).perform_later('world')
application._queueManger.add('HelloJob').set({wait: 5}).perform_later('world')
application._queueManger.add('HelloJob').set({wait: 5}).perform_later('world')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after1')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after2')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after3')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after4')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after5')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after6')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after7')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after8')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-afte9')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after10')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after11')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after12')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after13')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after14')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after15')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after17')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after19')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after20')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after21')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after22')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after23')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after24')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after25')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after26')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after27')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after28')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after29')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after30')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after31')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after32')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after33')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after34')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after35')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after36')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after37')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after38')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after39')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after40')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after41')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after42')
application._queueManger.add('HelloJob').set({wait: 20}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 21}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 22}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 23}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 24}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 25}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 26}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 27}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 28}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 29}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 30}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 31}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 32}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 33}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 34}).perform_later('world-after')
application._queueManger.add('HelloJob').set({wait: 35}).perform_later('world-after')